char* three[25] = {"air", "bog", "bud", "bug", "day", "den", "dew", "dig", "dry", "fly", "fog", "log", "low", "oil", "raw", "rot", "sap", "sun", "web", "wet", "fit", "top", "sea", "gas", "ray"};

char* four[45] = {"cave", "damp", "dirt", "drip", "drop", "dump", "east", "edge", "fall", "fern", "hive", "hole", "lake", "leaf", "mist", "mold", "nest", "pond", "rain", "rest", "ripe", "rock", "root", "salt", "soil", "stem", "tide", "tree", "weed", "west", "wind", "wood", "melt", "bite", "path", "wash", "mass", "hill", "lava", "life", "seed", "star", "moon", "fast", "slow"};

char* five[42] = {"adapt", "blade", "bloom", "brook", "cloud", "cycle", "fresh", "grass", "humid", "marsh", "night", "ocean", "plant", "river", "stone", "trash", "waste", "water", "ridge", "earth", "north", "south", "cliff", "gorge", "sleep", "moist", "steam", "coast", "sting", "renew", "flood", "erupt", "under", "joint", "float", "force", "repel", "solid", "larva", "orbit", "light", "sound"};

char* six[36] = {"absorb", "Arctic", "branch", "spring", "canopy", "canyon", "desert", "flower", "forest", "fungus", "growth", "insect", "mammal", "planet", "pollen", "stream", "system", "tundra", "valley", "ground", "winter", "summer", "rotten", "fossil", "nature", "matter", "energy", "record", "matter", "liquid", "motion", "sprout", "season", "magnet", "zigzag", "living"};

char* seven[43] = {"aquarium", "aquatic", "creature", "erosion", "extinct", "gravity", "habitat", "mangrove", "morning", "mountain", "recycle", "rotation", "sunrise", "survival", "weather", "mudslide", "sediment", "polluted", "monsoon", "fertile", "moisture", "variance", "extinct", "dispose", "describe", "melting", "freezing", "friction", "vibrate", "plates", "tsunami", "conserve", "omnivore", "drought", "function", "support", "offspring", "revolve", "pattern", "texture", "resource", "straight", "resemble"};

char* more[21] = {"pollution", "atmosphere", "condensation", "conservation", "ecosystem", "environment", "evaporate", "renewable", "hemisphere", "rockslide", "hibernate", "earthquake", "waterfall", "selection", "rainforest", "investigate", "temperature", "herbivore", "protection", "precipitation", "nonliving"};